version: "3"
services:
  cdk:
    image: aws_cdk_syniol:latest
    container_name: aws_cdk_syniol
    build:
      context: ..
      dockerfile: docker/Dockerfile
    privileged: true
    tty: true
    volumes:
      - "../:/usr/local/cdk"
    networks:
      - local_syniol_cdk_net

networks:
  local_syniol_cdk_net:
    driver: bridge
