name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag syniol/aws-cdk:latest
          echo "OK!"
      - uses: docker/login-action@v3
        with:
          username: syniol
          password: ${{ secrets.DOCKER_HUB_KEY }}
      - name: Login to Docker Hub
        run: docker push syniol/aws-cdk:latest
