name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag syniol/aws-cdk:${{  github.ref_name }}
          echo "OK!"
      - uses: docker/login-action@v3
        with:
          username: syniol
          password: ${{ secrets.DOCKER_HUB_KEY }}
      - name: Login to Docker Hub
        run: |
	  docker push syniol/aws-cdk:${{  github.ref_name }}
	  docker push syniol/aws-cdk:latest
